USE student_assignment_tracker;

-- Note:
-- Password hashes are generated by scripts/db-seed.js.
-- This SQL seed file is included for project review requirements.

INSERT INTO users (name, email, password_hash, role)
VALUES
('Admin User', 'admin@example.com', '$2b$10$examplehashforreviewonly', 'admin'),
('Teacher User', 'teacher@example.com', '$2b$10$examplehashforreviewonly', 'teacher'),
('Student User', 'student@example.com', '$2b$10$examplehashforreviewonly', 'student');

INSERT INTO courses (name, code, teacher_id)
VALUES
('Business Informatics', 'BI101', 2),
('Project Management', 'PM201', 2),
('Database Fundamentals', 'DB301', 2);

INSERT INTO enrollments (student_id, course_id)
VALUES
(3, 1),
(3, 2),
(3, 3);

INSERT INTO assignments (course_id, title, description, due_date, priority)
VALUES
(1, 'ERD Design', 'Create an ERD for the student assignment tracker.', '2026-07-05', 'High'),
(2, 'Project Charter', 'Prepare a simple project charter.', '2026-07-08', 'Medium'),
(3, 'SQL Practice', 'Submit SQL queries with screenshots.', '2026-07-12', 'Low');

INSERT INTO submissions (assignment_id, student_id, status, submitted_at, grade, feedback, notes)
VALUES
(1, 3, 'submitted', NOW(), NULL, NULL, 'Submitted for review.'),
(2, 3, 'graded', NOW(), 88.00, 'Good work.', 'Project charter submitted.');